### ISSUE TITLE
Download not possible anymore

### ISSUE THREAD

**Issue by eserte** [0xxon/alien-nss#3]
When trying to build the distribution I get the following:

```
Output from '/usr/perl5.22.0p/bin/perl5.22.0 Build.PL':

+ pkg-config --modversion nss

Architecture: amd64

Searching current download directory on FTP server...
Cannot connect to repository host: Operation timed out at Build.PL line 122.
```

http://fast-matrix.cpantesters.org/?dist=Alien-NSS;reports=1#sl=7,1 shows that UNKNOWN reports start from 2015-08-08, so maybe it's a permanent problem...

**Comment by 0xxon** [comment]
Yup -- apparently Mozilla switched of ftp access to ftp.mozilla.org. Sorry about that, I will try to fix that in the next few days... that needs a bit of rewriting things.
